AWSTemplateFormatVersion: "2010-09-09"
Description: This template sets up a EC2 instance.

Resources:
  MyInstances: 
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-087c17d1fe0178315
      InstanceType: t2.micro