AWSTemplateFormatVersion: "2010-09-09"
Description: This template prOvision a S3 bucket.

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: bucketfelipedias